export const sampleDocuments = [
  {
    id: "doc_001",
    filename: "remote_work_policy.pdf",
    original_filename: "Remote Work Policy 2024.pdf",
    file_size: 156800,
    file_type: "pdf",
    uploaded_at: "2024-03-15T09:30:00Z",
    processed_at: "2024-03-15T09:31:23Z",
    author: "HR Department",
    title: "Remote Work Policy Guidelines",
    category: "Policy",
    department: "HR",
    tags: ["remote work", "policy", "guidelines", "2024"],
    confidentiality_level: "Internal",
    year: 2024,
    language: "en",
    page_count: 8,
    chunk_count: 32,
    processing_status: "completed",
    error_message: null,
    content_preview:
      "This policy establishes guidelines for remote work arrangements. Employees are eligible for remote work if they demonstrate consistent performance and have manager approval. Remote work requires dedicated workspace and reliable internet connection...",
  },
  {
    id: "doc_002",
    filename: "vacation_faq.pdf",
    original_filename: "Vacation and PTO FAQ.pdf",
    file_size: 89600,
    file_type: "pdf",
    uploaded_at: "2024-02-20T14:15:00Z",
    processed_at: "2024-02-20T14:16:45Z",
    author: "HR Team",
    title: "Vacation and PTO Frequently Asked Questions",
    category: "FAQ",
    department: "HR",
    tags: ["vacation", "PTO", "FAQ", "benefits"],
    confidentiality_level: "Internal",
    year: 2024,
    language: "en",
    page_count: 5,
    chunk_count: 18,
    processing_status: "completed",
    error_message: null,
    content_preview:
      "Q: How do I request vacation time? A: Submit a request through the HR portal at least 2 weeks in advance. Q: What is the maximum vacation days I can carry over? A: Employees can carry over up to 5 vacation days to the next calendar year...",
  },
  {
    id: "doc_003",
    filename: "engineering_guidelines.pdf",
    original_filename: "Engineering Best Practices 2024.pdf",
    file_size: 234500,
    file_type: "pdf",
    uploaded_at: "2024-03-10T11:45:00Z",
    processed_at: "2024-03-10T11:47:12Z",
    author: "Engineering Team",
    title: "Engineering Best Practices and Guidelines",
    category: "Manual",
    department: "Engineering",
    tags: ["engineering", "best practices", "guidelines", "development"],
    confidentiality_level: "Internal",
    year: 2024,
    language: "en",
    page_count: 15,
    chunk_count: 58,
    processing_status: "completed",
    error_message: null,
    content_preview:
      "This document outlines coding standards, architecture patterns, and development practices for the engineering team. All code must follow the established linting rules and undergo peer review. Security considerations should be integrated from the design phase...",
  },
];

export const sampleQueries = [
  {
    id: "query_001",
    query: "What is the remote work policy?",
    filters: { department: "HR", category: "Policy" },
    expected_sources: ["doc_001"],
    sample_answer:
      "According to our Remote Work Policy Guidelines, employees are eligible for remote work arrangements if they demonstrate consistent performance and receive manager approval. The policy requires a dedicated workspace and reliable internet connection. Remote work requests should be submitted through the proper channels with advance notice.",
  },
  {
    id: "query_002",
    query: "How do I request vacation time?",
    filters: { department: "HR", category: "FAQ" },
    expected_sources: ["doc_002"],
    sample_answer:
      "To request vacation time, you should submit a request through the HR portal at least 2 weeks in advance. This ensures proper coverage and approval workflow. For specific questions about vacation balances or policies, refer to the Vacation and PTO FAQ document.",
  },
  {
    id: "query_003",
    query: "What are the latest engineering guidelines for code review?",
    filters: { department: "Engineering", year: 2024 },
    expected_sources: ["doc_003"],
    sample_answer:
      "According to the Engineering Best Practices 2024, all code must undergo peer review before deployment. The guidelines specify that code should follow established linting rules, security considerations should be integrated from the design phase, and architecture patterns should be consistent across the team.",
  },
];
